### ISSUE TITLE
Homepage UX punch-list 2021Q2

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#100]
Below is a list of all of the changes listed under the "Homepage" heading in @ACharbonneau 's [document](https://docs.google.com/document/d/1tYtBXL3HmxSbyA8lVwCvXQKQI6xssoL3pur65RyRxoY/edit#heading=h.ukdyqvjnli2).

## Homepage UX changes:
 - [x] Change Default plot: #83 
 - [x] ~Revisit clickable bricks: #6~ 
 - Wording changes:
   - [x] Summary View <- Preview the data
   - [x] Explore our Repository <- Get Started
     - currently called "Start your search", so maybe this shouldn't be changed again
   - [x] Browse all data <- Data Browser 
 - [x] #102 

## General Plot UX changes: 
 - [image here](https://drive.google.com/file/d/1O2wkGGjS_oa00HBiSV9bfkwM7SqypdtG/view)
 - [x] Reorder plot colors: #88
 - [x] Move download button on plots down below the legend (inline with axis options)
   - for "My Dashboard" plot, this button is gone.. is that intentional?
 - rearrange axis options
   - should this apply to "My Dashboard" plot too?
   - [x] "y axis" is first (more adjacent to the y-axis)
   - [x] "x axis" below x axis (inline with y-axis dropdown and download button)
   - [x] "stack by" is above the legend
 - Wording changes:
   - [x] change "Stack by" to "Group by"
   - [x] change "Unknown" to "Not specified" (#89 ) unknown value
     - all locations of unknowns
        <img src="https://user-images.githubusercontent.com/2932600/132790875-17f9fabe-3c36-4528-b257-f539bb3008ce.png" height=250 width=300 />
        <img src="https://user-images.githubusercontent.com/2932600/132790667-f079cf1b-bed7-4912-903e-201b0f138d25.png" height=250 width=300 />
 - [x] Update plot tooltips to include the x axis, y axis, and group by selections
   - Make plot tooltips wide enough for text 
     - e.g. "L1000 mRNA profiling assay (provisional OBI term)" doesn't currently fit in tooltip but fits in
 - [x] Change ‘unknown’ tooltip to explain what unknown means 
   - unknown brick?
   - unknown axis label?
 - [x] (provisional OBI term) should not be displayed. Users do not care
   - not going to be changed
 - [x] curate assay terms to not all end in "assay"
   - not going to be changed
 - [x] Get rid of ‘other’. Just plot everything. We can repeat colors and scroll the legend (#87 )
   - is all data shown in legend without a scroll currently?
   - should this apply to x axis also?
     - graph should not scroll along the x axis
     - if graph gets too wide we can add asterisk with tooltip saying the rest of the data is not included
