### ISSUE TITLE
Epic 1 testing findings

### ISSUE THREAD

**Issue by RLC-DCPPC** [nih-cfde/dashboard#16]
From @carlkesselman:

- [x] the C2M2 link on this page is bad:
          https://cfde-published-documentation.readthedocs-hosted.com/en/latest/
          the link in the menu bar is ok.
- [x] the labels on the bottom of the bar chart are cut off if the X-Axis is assay
and label on Samples by Anatomy and CF Program protrudes into the chart to the left.
- [x] The labeling on the Subjects by Assay and Anatomy chart is wanky... the order should be such that the line

- a side note, the style on the menu bar in the documentation is not consistent with the dashboard/portal... something to add to the list....
   - this will be handled outside of this issue

**Comment by jonathancrabtree** [comment]
The last item above is truncated, but the issue is that the lines between the labels and the corresponding donut slices can cross one another (usually in cases where there are multiple adjacent small slices):

![donut-overlaps](https://user-images.githubusercontent.com/5394345/100646193-b50b3700-330b-11eb-98f4-2d061bca164f.png)

There are also two issues with the mouse hover popups. The first popup issue is that the popup box is a fixed size and the label doesn't always fit:

![popup-issue-1](https://user-images.githubusercontent.com/5394345/100646835-95284300-330c-11eb-9247-9cc0cea0189b.png)

The second popup issue is that the relative position of the popup div doesn't change when you're near the top and/or left edge of the graph and so part of the popup can be missing. In the following example (which actually illustrates both issues) the label should say "16s ribosomal..." not just "ribosomal":

![popup-issue-2](https://user-images.githubusercontent.com/5394345/100647071-f9e39d80-330c-11eb-9b6a-5e0bad8d5fa0.png)

**Comment by jonathancrabtree** [comment]
Committed some initial steps to address the label overflows:
- Reduced whitespace and changed angle of labels.
- The last/rightmost label is truncated sooner than the rest due to the reduced space (could be improved further by reducing left margin and adding space between the graph and the color legend.)
- Labels are now explicitly truncated with "..." used to indicate incompleteness.
- Title elements have been added to enable full label display on mouseover (see 2nd screenshot below)

![Screen Shot 2020-12-09 at 3 43 07 PM](https://user-images.githubusercontent.com/5394345/101685434-bcca8a00-3a35-11eb-93f9-11720ff0158c.png)

![Screen Shot 2020-12-09 at 3 23 17 PM](https://user-images.githubusercontent.com/5394345/101685936-5e51db80-3a36-11eb-8d69-100296fed528.png)

**Comment by jonathancrabtree** [comment]
As the preceding screenshots show, there's quite a bit of variability in the amount of vertical whitespace between the graph and the form controls below. This should be standardized and then the labels allowed to extend as far as possible into that space.

**Comment by victor73** [comment]
Made some commits to address issues with the tooltips going out-of-bounds in some cases and dynamically truncating/ellipsizing long category names to fit inside the tooltip borders.

**Comment by jonathancrabtree** [comment]
Switched donut charts to use a color legend instead of attaching labels. Also fixed problems with the donut chart color assignments and tooltip label overruns:

![Screen Shot 2020-12-11 at 12 18 56 AM](https://user-images.githubusercontent.com/5394345/101866378-a4966000-3b46-11eb-8bdd-4299dc9a74bd.png)

**Comment by jonathancrabtree** [comment]
One more addition to the donut chart, which is to enable mouse hover on the legend as well as the chart itself:

![Screen Shot 2020-12-15 at 12 20 48 PM](https://user-images.githubusercontent.com/5394345/102249991-fb968f00-3ed0-11eb-90cd-19bce662b46e.png)

We can revisit the use of direct labels with connecting lines if this approach proves inadequate.
